nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    allow_methods: ['GET']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Link']
    max_age: 3600
  paths:
    '^/catalogue': ~
    '^/login':
      allow_methods: ['POST']
    '^/nous-contacter':
      allow_methods: ['POST']
    '^/profile':
      allow_methods: ['GET', 'POST']
    '^/liste-favoris':
      allow_methods: ['GET', 'POST']
    '^/dashboard':
      allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE']
